repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --check
        language: system
        pass_filenames: false
        types: [rust]
      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy --all-targets
        language: system
        pass_filenames: false
        types: [rust]
      # - id: cargo-miri
      #   name: cargo miri
      #   entry: cargo miri test --all-targets
      #   language: system
      #   pass_filenames: false
      #   types: [rust]
